services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trading-dashboard-backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:80,http://frontend:80
      - ORDERS_DIR=orders
      - SYMBOLS_FILE=symbols.json
    volumes:
      - ./backend/symbols.json:/app/symbols.json:ro
      - orders_data:/app/orders
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./trading-dashboard-frontend
      dockerfile: Dockerfile
    container_name: trading-dashboard-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000/api
      - REACT_APP_WS_BASE_URL=ws://localhost:8000/ws/ticks
    networks:
      - trading-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  orders_data:
    driver: local

networks:
  trading-network:
    driver: bridge
